### ISSUE TITLE
Not working Link

### ISSUE THREAD

**Issue by sultanien** [HackYourFuture/study#18]
When I check the link above in "https://hackyourfuture.github.io/study/#/javascript/operators", it gives me 404 not found. 

Also check out [special characters and their names](https://hackyourfuture.github.io/study/#/names_of_special_characters)

**Comment by robvk** [comment]
I have fixed the link on the special characters page, not sure which link you mean on this page: https://hackyourfuture.github.io/study/#/javascript/operators.

Thanks for letting us know!

**Comment by sultanien** [comment]
Actually the link I mention : https://hackyourfuture.github.io/study/#/names_of_special_characters and it does not still work.
