### ISSUE TITLE
Value in a table in "What is Structured Query Language (SQL)?" looks weird

### ISSUE THREAD

**Issue by SergPerep** [HackYourFuture/study#19]
There is a table in [README.md "What is Structured Query Language (SQL)?"](https://github.com/HackYourFuture/study/blob/master/databases/sql/README.md) which seems fine on GitHub. But on [hackyourfuture.github.io](https://hackyourfuture.github.io/study/#/databases/sql/README) it looks weird.
![image](https://user-images.githubusercontent.com/30504467/185974787-4d87f412-bf79-4c65-a315-85d4ecfc7f3a.png)

**Comment by robvk** [comment]
It seemed to want to make an emoji. Fixed it, thanks!
